const productRange = [
    {no: `1`,
    id: `G1`,
    type: `General`,
    title: `Love & Relationships`,
    spread: `Spread: 5 - 7 tarot cards + chakra`,
    price: `35`,
    para1: ``,
    para2: ``,
    para3: ``,
    invoicename: `General: Love & Relationships reading`,
    imageSrc: `LR.jpg`,
    textAreaHeader: `Anything you'd like to share ...`,
    textAreaElement: `textarea`,
    textAreaRequired: `false`,     
    },

    {no: `2`,
        id: `G2`,
        type: `General`,
        title: `Career & Finances`,
        spread: `Spread: 5 - 7 tarot card + chakra`,
        price: `35`,
        para1: ``,
        para2: ``,
        para3: ``,
        invoicename: `General: Career & Finance reading`,
        imageSrc: `CF.jpg`,
        textAreaHeader: `Anything you'd like to share ...`,
        textAreaElement: `textarea`,
        textAreaRequired: `false`,     
        },

        {   no: `3`, 
            id: `G3`,
            type: `General`,
            title: `Health & Well-Being`,
            spread: `Spread: 5 - 7 tarot cards + 1 chakra`,
            price: `35`,
            para1: ``,
            para2: ``,
            para3: ``,
            invoicename: `General: Health & Well-Being reading`,
            imageSrc: `HWB.jpg`,
            textAreaHeader: `Anything you'd like to share ...`,
            textAreaElement: `textarea`,
            textAreaRequired: `false`,     
            },

            {   no: `4`,
                id: `G4`,
                type: `General`,
                title: `Home & Family`,
                spread: `Spread: 5 - 7 tarot cards + chakra`,
                price: `35`,
                para1: ``,
                para2: ``,
                para3: ``,
                invoicename: `General: Home & Family reading`,
                imageSrc: `HF.jpg`,
                textAreaHeader: `Anything you'd like to share ...`,
                textAreaElement: `textarea`,
                textAreaRequired: `false`,     
                },

                {   no: `5`, 
                    id: `G5`,
                    type: `General`,
                    title: `Revelations`,
                    spread: `Spread: 5 - 7 tarot cards + chakra`,
                    price: `35`,
                    para1: ``,
                    para2: ``,
                    para3: ``,
                    invoicename: `General: Revelations reading`,
                    imageSrc: `RVL.jpg`,
                    textAreaHeader: `Anything you'd like to share ...`,
                    textAreaElement: `textarea`,
                    textAreaRequired: `false`,     
                    },

                    {   no: `6`,
                        id: `Q1`,
                        type: `Specific`,
                        title: `You pose the question or issue`,
                        spread: `Spread: 5 - 7 tarot cards + chakra`,
                        price: `35`,
                        para1: ``,
                        para2: ``,
                        para3: ``,
                        invoicename: `Specific: 5 card reading`,
                        imageSrc: `SQ5.jpg`,
                        textAreaHeader: `Enter the question or issue you have for the cards here ...`,
                        textAreaElement: `textarea`,
                        textAreaRequired: `true`,
                        },

                        {   no: `7`,
                            id: `Q2`,
                            type: `Specific`,
                            title: `You pose the question or issue`,
                            spread: `Spread:10 - 12 tarot cards + chakra`,
                            price: `60`,
                            para1: ``,
                            para2: ``,
                            para3: ``,
                            invoicename: `Specific: 10 card reading`,
                            imageSrc: `SQ10.jpg`,
                            textAreaHeader: `Enter the question or issue you have for the cards here ...`,
                            textAreaElement: `textarea`,
                            textAreaRequired: `true`,     
                            },

                            {   no: `8`,
                                id: `F1`,
                                type: `Forecast`,
                                title: `In-depth 12 mth forecast`,
                                spread: `2 x 12 card spreads + chakras`,
                                price: `120`,
                                para1: ``,
                                para2: ``,
                                para3: ``,
                                invoicename: `Forecast: a look at the next 12 months in detail`,
                                imageSrc: `FC.jpg`,
                                textAreaHeader: ``,
                                textAreaElement: ``,
                                textAreaRequired: ``,     
                                },

                                {   no: `9`,
                                    id: `B1`,
                                    type: `Bundle`,
                                    title: `Love & Relationships`,
                                    spread: `Two 5 - 7 tarot card spreads + chakra`,
                                    price: `60`,
                                    para1: ``,
                                    para2: ``,
                                    para3: ``,
                                    invoicename: `Bundle: Love & relationships readings`,
                                    imageSrc: `LRB.jpg`,
                                    textAreaHeader: `Anything you'd like to share ...`,
                                    textAreaElement: `textarea`,
                                    textAreaRequired: `false`,     
                                    },

                                    {   no: `10`,
                                        id: `B2`,
                                        type: `Bundle`,
                                        title: `Career & Finances`,
                                        spread: `Two 5 - 7 tarot card spreads + chakra`,
                                        price: `60`,
                                        para1: ``,
                                        para2: ``,
                                        para3: ``,
                                        invoicename: `Bundle: Career & Finance readings`,
                                        imageSrc: `CFB.jpg`,
                                        textAreaHeader: `Anything you'd like to share ...`,
                                        textAreaElement: `textarea`,
                                        textAreaRequired: `false`,
                                        },

                                        {   no: `11`,
                                            id: `B3`,
                                            type: `Bundle`,
                                            title: `Health & Well-Being`,
                                            spread: `Two 5 - 7 tarot card spreads + chakra`,
                                            price: `60`,
                                            para1: ``,
                                            para2: ``,
                                            para3: ``,
                                            invoicename: `Bundle: Health & Well-being readings`,
                                            imageSrc: `HWBB.jpg`,
                                            textAreaHeader: `Anything you'd like to share ...`,
                                            textAreaElement: `textarea`,
                                            textAreaRequired: `false`,     
                                            },
                                           
                                            {   no: `12`,
                                                id: `B4`,
                                                type: `Bundle`,
                                                title: `Revelations`,
                                                spread: `Four 5 - 7 tarot card spreads + chakra`,
                                                price: `100`,
                                                para1: ``,
                                                para2: ``,
                                                para3: ``,
                                                invoicename: `Bundle: Revelations readings`,
                                                imageSrc: `RVLB.jpg`,
                                                textAreaHeader: `Anything you'd like to share ...`,
                                                textAreaElement: `textarea`,
                                                textAreaRequired: `false`,     
                                                },
                                                
                                                {   no: `13`,
                                                    id: `S1`,
                                                    type: `Subscription`,
                                                    title: `Bumper bundle of readings`,
                                                    spread: `16 tarot spreads + chakras`,
                                                    price: `45`,
                                                    para1: ``,
                                                    para2: ``,
                                                    para3: ``,
                                                    invoicename: `Subscription: 4 quarterly + 1 monthly tarot readings & chakras`,
                                                    imageSrc: `SUB.jpg`,
                                                    textAreaHeader: ``,
                                                    textAreaElement: ``,
                                                    textAreaRequired: ``,     
                                                    },

                                                    {   no: `14`,
                                                        id: `S2`,
                                                        type: `Subscription`,
                                                        title: `Reading for each new moon`,
                                                        spread: `Spread: 6 tarot cards + chakra`,
                                                        price: `40`,
                                                        para1: ``,
                                                        para2: ``,
                                                        para3: ``,
                                                        invoicename: `Subscription: monthly new moon reading`,
                                                        imageSrc: `NMSM.jpg`,
                                                        textAreaHeader: ``,
                                                        textAreaElement: ``,
                                                        textAreaRequired: ``,     
                                                        },
                                                        {   no: `15`, 
                                                            id: `S3`,
                                                            type: `Subscription`,
                                                            title: `A new moon reading / quarter`,
                                                            spread: `Spread: 6 tarot cards + chakra`,
                                                            price: `13`,
                                                            para1: ``,
                                                            para2: ``,
                                                            para3: ``,
                                                            invoicename: `Subscription: new moon reading (1 / quarter)`,
                                                            imageSrc: `NMSQ.jpg`,
                                                            textAreaHeader: ``,
                                                            textAreaElement: ``,
                                                            textAreaRequired: ``,     
                                                            }

];