const productRange = [
    {no: `1`,
    id: `G1`,
    type: `General`,
    title: `Love & Relationships`,
    spread: `Spread: 5 - 7 tarot cards + chakra`,
    price: `35.00`,
    para1: `A general reading designed to offer insight into the state of play in relation to the relationships in your life, whether they be romantic or platonic.`,
    para2: `If you’re having issues with a particular relationship or are struggling to make personal connections in general, the chakra insight can help identify ways to resolve those problems.`,
    para3: `Get the best out of this reading by only asking questions that relate to something within your power to control.`,
    invoicename: `General: Love & Relationships reading`,
    imageSrc: `LR.jpg`,
    textAreaHeader: `Anything you'd like to share ...`,
    textAreaElement: `textarea`,
    textAreaRequired: `false`,     
    },

    {no: `2`,
        id: `G2`,
        type: `General`,
        title: `Career & Finances`,
        spread: `Spread: 5 - 7 tarot card + chakra`,
        price: `35.00`,
        para1: `Thinking of changing jobs or switching career paths? A new business venture or investment opportunity? Then this is the reading for you.`,
        para2: `Without your input, a three-card spread offers a top-level insight. From here, another 5 to 7 cards are spread and any messages or insights the tarot has for you are included in your reading.`,
        para3: `Focus on a specific question or issue determines the spreads used, ensuring you gain maximum insight & benefit from the reading.`,
        invoicename: `General: Career & Finance reading`,
        imageSrc: `CF.jpg`,
        textAreaHeader: `Anything you'd like to share ...`,
        textAreaElement: `textarea`,
        textAreaRequired: `false`,     
        },

        {   no: `3`, 
            id: `G3`,
            type: `General`,
            title: `Health & Well-Being`,
            spread: `Spread: 5 - 7 tarot cards + 1 chakra`,
            price: `35.00`,
            para1: `Designed to identify & resolve issues impacting your general health & well-being.  Insights can relate to your physical, mental or spiritual self.`,
            para2: `Concerned a particular issue or situation is negatively impacting other areas of your life? Provide the details or questions at checkout to focus the reading specifically.`,
            para3: `The chakra is significant in this reading. Any energy imbalances or blockages are highlighted & ways to restore & clear them are offered.`,
            invoicename: `General: Health & Well-Being reading`,
            imageSrc: `HWB.jpg`,
            textAreaHeader: `Anything you'd like to share ...`,
            textAreaElement: `textarea`,
            textAreaRequired: `false`,     
            },

            {   no: `4`,
                id: `G4`,
                type: `General`,
                title: `Home & Family`,
                spread: `Spread: 5 - 7 tarot cards + chakra`,
                price: `35.00`,
                para1: `Expect crossover with other themes - they’re integrated with home & family life & can indicate underlying causes of any home or family issues.`,
                para2: `Share the details of any particular situation at home or with family you’d like to better understand or gain insight into how it could be resolved or overcome? `,
                para3: `The reading will be tailored specifically to provide you with actionable insights so your home & family life is happy & peaceful.`,
                invoicename: `General: Home & Family reading`,
                imageSrc: `HF.jpg`,
                textAreaHeader: `Anything you'd like to share ...`,
                textAreaElement: `textarea`,
                textAreaRequired: `false`,     
                },

                {   no: `5`, 
                    id: `G5`,
                    type: `General`,
                    title: `Revelations`,
                    spread: `Spread: 5 - 7 tarot cards + chakra`,
                    price: `35.00`,
                    para1: `If you’re more interested in what the universe has planned for you or where to focus your energy & attention, this is the reading for you.`,
                    para2: `A short tarot spread reveals the theme of focus & determines the type of spread used to communicate the message & intention the universe has for you.`,
                    para3: `The chakra highlights potential imbalances or blockages that may hinder or pinpointing a focal chakra to support & guide you.`,
                    invoicename: `General: Revelations reading`,
                    imageSrc: `RVL.jpg`,
                    textAreaHeader: ``,
                    textAreaElement: ``,
                    textAreaRequired: ``,     
                    },

                    {   no: `6`,
                        id: `Q1`,
                        type: `Specific`,
                        title: `You pose the question or issue`,
                        spread: `Spread: 5 - 7 tarot cards + chakra`,
                        price: `35.00`,
                        para1: `Designed to derive maximum benefit from a reading where you have a situation or problem that doesn’t neatly fit into just one theme. `,
                        para2: `You have total control of the reading & outcome by asking direct questions of the cards and providing context to your query. `,
                        para3: `Best used where the situation involves yourself and 1 or 2 others &/or relates to 1 or 2 general themes.`,
                        invoicename: `Specific: 5 card reading`,
                        imageSrc: `SQ5.jpg`,
                        textAreaHeader: `Enter the question or issue you have for the cards here ...`,
                        textAreaElement: `textarea`,
                        textAreaRequired: `true`,
                        },

                        {   no: `7`,
                            id: `Q2`,
                            type: `Specific`,
                            title: `You pose the question or issue`,
                            spread: `Spread:10 - 12 tarot cards + chakra`,
                            price: `60.00`,
                            para1: `Sometimes we’re confronted with complex situations involving various relationships, impacting several areas of day to day life.`,
                            para2: `This reading is especially designed for such a situation & aims to provide you with the insight & guidance needed to tackle it head on.`,
                            para3: `You’re empowered by the outcome with the context you provide & the questions you ask the cards to answer.`,
                            invoicename: `Specific: 10 card reading`,
                            imageSrc: `SQ10.jpg`,
                            textAreaHeader: `Enter the question or issue you have for the cards here ...`,
                            textAreaElement: `textarea`,
                            textAreaRequired: `true`,     
                            },

                            {   no: `8`,
                                id: `F1`,
                                type: `Forecast`,
                                title: `In-depth 12 mth forecast`,
                                spread: `2 x 12 card spreads + chakras`,
                                price: `120.00`,
                                para1: `Reading #1 looks 12mths ahead, highlighting what empowers you, obstacles you can expect to face, and the life lessons coming your way.`,
                                para2: `Insights into the four general themes are included. It also reveals your aspirations & the energy you’ll need to harness in order to achieve them.`,
                                para3: `The second reading is a monthly snapshot of what to be aware of & prepared for in order to grasp every opportunity & avoid any pitfalls.`,
                                invoicename: `Forecast: a look at the next 12 months in detail`,
                                imageSrc: `FC.jpg`,
                                textAreaHeader: ``,
                                textAreaElement: ``,
                                textAreaRequired: ``,     
                                },

                                {   no: `9`,
                                    id: `B1`,
                                    type: `Bundle`,
                                    title: `Love & Relationships`,
                                    spread: `Two 5 - 7 tarot card spreads + chakra`,
                                    price: `60.00`,
                                    para1: `Bundles a general Love & Relationship reading together with a more specific reading related to your personal situation.`,
                                    para2: `For singles, a reading centered around finding your soulmate offers insights into how to focus your energy & recognise when your path crosses with theirs.`,
                                    para3: `For couples, a reading crafted to deliver you insights into how best to understand the nature of your relationship & maximise its potential.`,
                                    invoicename: `Bundle: Love & relationships readings`,
                                    imageSrc: `LRB.jpg`,
                                    textAreaHeader: `Anything you'd like to share ...`,
                                    textAreaElement: `textarea`,
                                    textAreaRequired: `false`,     
                                    },

                                    {   no: `10`,
                                        id: `B2`,
                                        type: `Bundle`,
                                        title: `Career & Finances`,
                                        spread: `Two 5 - 7 tarot card spreads + chakra`,
                                        price: `60.00`,
                                        para1: ``,
                                        para2: ``,
                                        para3: ``,
                                        invoicename: `Bundle: Career & Finance readings`,
                                        imageSrc: `CFB.jpg`,
                                        textAreaHeader: `Anything you'd like to share ...`,
                                        textAreaElement: `textarea`,
                                        textAreaRequired: `false`,
                                        },

                                        {   no: `11`,
                                            id: `B3`,
                                            type: `Bundle`,
                                            title: `Health & Well-Being`,
                                            spread: `Two 5 - 7 tarot card spreads + chakra`,
                                            price: `60.00`,
                                            para1: ``,
                                            para2: ``,
                                            para3: ``,
                                            invoicename: `Bundle: Health & Well-being readings`,
                                            imageSrc: `HWBB.jpg`,
                                            textAreaHeader: `Anything you'd like to share ...`,
                                            textAreaElement: `textarea`,
                                            textAreaRequired: `false`,     
                                            },
                                           
                                            {   no: `12`,
                                                id: `B4`,
                                                type: `Bundle`,
                                                title: `Revelations`,
                                                spread: `Four 5 - 7 tarot card spreads + chakra`,
                                                price: `100.00`,
                                                para1: ``,
                                                para2: ``,
                                                para3: ``,
                                                invoicename: `Bundle: Revelations readings`,
                                                imageSrc: `RVLB.jpg`,
                                                textAreaHeader: `Anything you'd like to share ...`,
                                                textAreaElement: `textarea`,
                                                textAreaRequired: `false`,     
                                                },
                                                
                                                {   no: `13`,
                                                    id: `S1`,
                                                    type: `Subscription`,
                                                    title: `Bumper bundle of readings`,
                                                    spread: `16 tarot spreads + chakras`,
                                                    price: `45.00`,
                                                    para1: ``,
                                                    para2: ``,
                                                    para3: ``,
                                                    invoicename: `Subscription: 4 quarterly + 1 monthly tarot readings & chakras`,
                                                    imageSrc: `SUB.jpg`,
                                                    textAreaHeader: ``,
                                                    textAreaElement: ``,
                                                    textAreaRequired: ``,     
                                                    },

                                                    {   no: `14`,
                                                        id: `S2`,
                                                        type: `Subscription`,
                                                        title: `Reading for each new moon`,
                                                        spread: `Spread: 6 tarot cards + chakra`,
                                                        price: `40.00`,
                                                        para1: ``,
                                                        para2: ``,
                                                        para3: ``,
                                                        invoicename: `Subscription: monthly new moon reading`,
                                                        imageSrc: `NMSM.jpg`,
                                                        textAreaHeader: ``,
                                                        textAreaElement: ``,
                                                        textAreaRequired: ``,     
                                                        },
                                                        {   no: `15`, 
                                                            id: `S3`,
                                                            type: `Subscription`,
                                                            title: `A new moon reading / quarter`,
                                                            spread: `Spread: 6 tarot cards + chakra`,
                                                            price: `13.00`,
                                                            para1: ``,
                                                            para2: ``,
                                                            para3: ``,
                                                            invoicename: `Subscription: new moon reading (1 / quarter)`,
                                                            imageSrc: `NMSQ.jpg`,
                                                            textAreaHeader: ``,
                                                            textAreaElement: ``,
                                                            textAreaRequired: ``,     
                                                            }

];